"use client";

import { useEffect, useRef, useState } from "react";
import {
  Activity, ArrowRight, BarChart3, Calendar, Check, CircleCheck, Cloud, Database,
  Download, FileText, Film, Gauge, HeartPulse, Link2, Lock, MapPin, MoreHorizontal,
  Plus, RefreshCw, Search, Send, Settings, ShieldCheck, Sparkles, Target, Trophy,
  Upload, UserPlus, Users, Video, Watch, Waves,
} from "lucide-react";
import { athletes, connectors, insights, meets, season, videos, zoneDistribution } from "./demo-data";
import { Avatar, Metric, PageTitle, SectionHead, StatusDot } from "./components";
import type { AppView } from "./views-primary";
import { apiRequest, mediaUrl, uploadFile } from "./api";
import { csvRow, downloadFile } from "./client-utils";

export function Season({ onMeet, onSettings, onCreateMeet, onNotify }: { onMeet: (id: string) => void; onSettings: () => void; onCreateMeet: () => void; onNotify: (message: string) => void }) {
  return <>
    <PageTitle kicker="TEMPORADA" title={season.name} subtitle={`${season.starts} - ${season.ends} | semana ${season.week} de ${season.totalWeeks}`}><button className="secondary-button" onClick={onSettings}><Settings size={17} />Ajustes</button><button className="primary-button" onClick={onCreateMeet}><Plus size={17} />Nova competição</button></PageTitle>
    <section className="card season-overview"><div className="season-progress"><div><span>PROGRESSO DA TEMPORADA</span><strong>8%</strong></div><div className="long-progress"><i style={{ width: "8%" }} /></div><div><small>Início · 04 ago</small><small>Hoje · semana 4</small><small>Principal · 18 set</small><small>Fim · 19 jul</small></div></div><div className="phase-timeline">{season.phases.map((phase) => <article key={phase.name}><span style={{ background: phase.color }} /><div><em style={{ color: phase.color }}>{phase.focus}</em><b>{phase.name}</b><small>{phase.start} - {phase.end}</small></div>{phase.progress > 0 && <i style={{ width: `${phase.progress}%`, background: phase.color }} />}</article>)}<button onClick={() => onNotify("Editor de fase aberto com foco, datas e competição-alvo.")}><Plus size={16} />Adicionar fase</button></div></section>
    <section className="season-columns"><div className="card"><SectionHead title="Próximas competições" subtitle="Prioridades, índices e inscrições" action="Calendário completo" onAction={() => onNotify("Calendário anual exibido com fases e competições.")} /><div className="meet-list">{meets.map((meet) => <button key={meet.id} onClick={() => onMeet(meet.id)}><span className={`meet-priority p${meet.priority.toLowerCase()}`}>{meet.priority}</span><div><b>{meet.name}</b><small><MapPin size={13} />{meet.location} · {meet.pool}</small></div><div><strong>{meet.date}</strong><small>em {meet.days} dias</small></div><div><b>{meet.qualified}</b><small>com índice</small></div><ArrowRight size={16} /></button>)}</div></div><aside className="card readiness-to-meet"><SectionHead title="Prontidão para o alvo" subtitle="Troféu Brasil · 21 dias" /><div className="radar-placeholder"><div className="radar-ring r1" /><div className="radar-ring r2" /><div className="radar-ring r3" /><span style={{ top: "8%", left: "45%" }}>Saída 78</span><span style={{ top: "44%", right: "1%" }}>Velocidade 84</span><span style={{ bottom: "3%", right: "14%" }}>Virada 72</span><span style={{ bottom: "3%", left: "12%" }}>Ritmo 81</span><span style={{ top: "44%", left: "1%" }}>Chegada 76</span><i /></div><div className="meet-readiness-score"><strong>78</strong><span>Índice composto da equipe</span><em className="positive">↑ 4 pontos no ciclo</em></div></aside></section>
  </>;
}

type VideoListItem = { id: string; athlete: string; initials: string; color: string; event: string; time: string; date: string; status: string; duration: string; markers: number; real?: boolean; url?: string; thumbnailUrl?: string };

export function Videos({ onVideo, onNotify }: { onVideo: (id: string) => void; onNotify: (message: string) => void }) {
  const [filter, setFilter] = useState("Todos");
  const [query, setQuery] = useState("");
  const [catalog, setCatalog] = useState<VideoListItem[]>(videos);
  const uploadInput = useRef<HTMLInputElement>(null);
  const loadVideos = async () => {
    try {
      const result = await apiRequest<{ data: Array<Record<string, unknown> & { id: string }> }>("/api/v1/manage/videos");
      const remote = result.data.map((record, index): VideoListItem => ({ id: record.id, athlete: String(record.athlete ?? athletes.find((athlete) => athlete.id === record.athleteId)?.name ?? "Atleta não definido"), initials: String(record.athlete ?? "AN").split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase(), color: ["#7357ef", "#0da98b", "#397ac4", "#e35f65"][index % 4], event: String(record.event ?? record.title ?? "Sessão técnica"), time: typeof record.durationSeconds === "number" ? `${Number(record.durationSeconds).toFixed(2).replace(".", ",")} s` : "Processando", date: "28 ago", status: record.analysisStatus === "ready" ? "review" : String(record.status ?? "review"), duration: typeof record.durationSeconds === "number" ? `00:${String(Math.round(Number(record.durationSeconds))).padStart(2, "0")}` : "-", markers: Number((record.analysis as { events?: unknown[] } | undefined)?.events?.length ?? 0), real: true, url: String(record.url ?? ""), thumbnailUrl: String(record.thumbnailUrl ?? "") }));
      if (remote.length) setCatalog(remote);
    } catch { /* mantém catálogo local se a API estiver indisponível */ }
  };
  useEffect(() => { void loadVideos(); }, []);
  const shown = catalog.filter((video) => (filter === "Todos" || (filter === "Para revisar" && video.status === "review") || (filter === "Revisados" && video.status === "done")) && `${video.athlete} ${video.event}`.toLowerCase().includes(query.toLowerCase()));
  const handleUpload = async (file?: File) => {
    if (!file) return;
    try {
      const record = await uploadFile(file, "videos");
      onNotify("Vídeo armazenado. A análise de movimento foi iniciada.");
      if (typeof record.id === "string") await apiRequest(`/api/v1/videos/${record.id}/analyze`, { method: "POST", headers: { "Content-Type": "application/json" }, body: "{}" });
      await loadVideos();
    } catch (error) { onNotify(error instanceof Error ? error.message : "Falha ao enviar vídeo"); }
  };
  return <><PageTitle kicker="ANÁLISE TÉCNICA" title="Vídeos de prova e treino" subtitle="Movimento, ciclos e evidências técnicas sincronizados ao vídeo real."><button className="secondary-button" onClick={() => onNotify("Modo deck aberto: câmera, cronômetro e registro de prova preparados.")}><Video size={17} />Gravar no deck</button><input ref={uploadInput} hidden type="file" accept="video/*" onChange={(event) => void handleUpload(event.target.files?.[0])} /><button className="primary-button" onClick={() => uploadInput.current?.click()}><Upload size={17} />Enviar vídeo</button></PageTitle>
    <div className="video-stats"><div><Film size={19} /><span><b>24</b> provas filmadas</span></div><div><Activity size={19} /><span><b>2</b> aguardando revisão</span></div><div><BarChart3 size={19} /><span><b>4</b> esta semana</span></div></div>
    <div className="roster-toolbar video-toolbar"><div className="filter-pills">{["Todos", "Para revisar", "Revisados"].map((item) => <button key={item} className={filter === item ? "active" : ""} onClick={() => setFilter(item)}>{item}</button>)}</div><div className="local-search"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Atleta ou prova" /></div></div>
    <section className="video-grid">{shown.map((video, index) => <article className="card video-card" key={video.id}><button className="video-thumb" onClick={() => onVideo(video.id)}><div className={`pool-frame frame-${index + 1}`}>{video.thumbnailUrl ? <img src={mediaUrl(video.thumbnailUrl)} alt={`Quadro de ${video.event}`} /> : <><span className="lane-line l1" /><span className="lane-line l2" /><span className="lane-line l3" /></>}<i>▶</i><em>{video.duration}</em><span className="real-video-chip">ANÁLISE REAL</span></div></button><div className="video-meta"><div><Avatar initials={video.initials} color={video.color} small /><span><b>{video.athlete}</b><small>{video.date}</small></span><span className={video.status === "review" ? "review-badge" : "done-badge"}>{video.status === "review" ? "Para revisar" : video.status === "processing" ? "Processando" : "Revisado"}</span></div><h3>{video.event} · {video.time}</h3><div><span><Sparkles size={14} />{video.markers} eventos detectados</span><button onClick={() => onVideo(video.id)}>Abrir análise<ArrowRight size={15} /></button></div></div></article>)}</section></>;
}

export function Analytics({ onAthlete, onNotify }: { onAthlete: (id: string) => void; onNotify: (message: string) => void }) {
  const [weeks, setWeeks] = useState(8);
  const [metric, setMetric] = useState<"volume" | "carga">("volume");
  const [descending, setDescending] = useState(true);
  const [classic, setClassic] = useState(false);
  const goalAthletes = [...athletes.filter((athlete) => athlete.goalEvent)].sort((a, b) => descending ? String(b.gap).localeCompare(String(a.gap)) : String(a.gap).localeCompare(String(b.gap)));
  const exportReport = () => {
    const rows = [csvRow(["Atleta", "Objetivo", "Gap", "Presença", "Readiness"]), ...athletes.map((athlete) => csvRow([athlete.name, athlete.goalEvent ?? "Sem meta", athlete.gap ?? "-", `${athlete.attendance}%`, athlete.readiness ?? "Sem dado"]))];
    downloadFile(`analise-programa-${weeks}-semanas.csv`, rows.join("\n"));
    onNotify("Relatório executivo exportado em CSV.");
  };
  return <><PageTitle kicker="INTELIGÊNCIA DO PROGRAMA" title="Análise" subtitle="Do planejamento à prova: uma leitura executiva do elenco."><button className="secondary-button" onClick={() => setWeeks((value) => value === 4 ? 8 : value === 8 ? 12 : 4)}><Calendar size={17} />Últimas {weeks} semanas</button><button className="primary-button" onClick={exportReport}><Download size={17} />Exportar relatório</button></PageTitle>
    <div className="metric-grid"><Metric label="ADERÊNCIA À CARGA" value="93,4%" detail="Prescrito × realizado" icon={Target} /><Metric label="EVOLUÇÃO DE PBS" value="+12" detail="Nos últimos 90 dias" icon={Trophy} tone="violet" /><Metric label="SAÚDE DO ELENCO" value="82%" detail="Sem alertas críticos" icon={HeartPulse} tone="blue" /><Metric label="COBERTURA DE DADOS" value="84%" detail="5 de 6 com wearable" icon={Database} tone="orange" /></div>
    <section className={`analytics-grid ${classic ? "classic-view" : ""}`}><article className="card program-volume"><SectionHead title={metric === "volume" ? "Volume do time por zona" : "Carga interna por semana"} subtitle={`Prescrito × realizado · ${weeks} semanas`} action="Trocar métrica" onAction={() => setMetric((value) => value === "volume" ? "carga" : "volume")} /><div className="chart-y-labels"><span>{metric === "volume" ? "40 km" : "900 u.a."}</span><span>{metric === "volume" ? "30 km" : "675 u.a."}</span><span>{metric === "volume" ? "20 km" : "450 u.a."}</span><span>{metric === "volume" ? "10 km" : "225 u.a."}</span><span>0</span></div><div className="stacked-chart">{[74, 82, 76, 91, 88, 84, 96, 93].map((total, i) => <div key={i} style={{ height: `${metric === "volume" ? total : Math.max(35, total - 9)}%` }}><span style={{ height: "28%", background: zoneDistribution[0].color }} /><span style={{ height: "34%", background: zoneDistribution[1].color }} /><span style={{ height: "19%", background: zoneDistribution[2].color }} /><span style={{ height: "11%", background: zoneDistribution[3].color }} /><span style={{ height: "8%", background: zoneDistribution[4].color }} /><small>S{i + 1}</small></div>)}</div><div className="zone-legend">{zoneDistribution.map((zone) => <span key={zone.code}><i style={{ background: zone.color }} />{zone.code}</span>)}</div></article>
      <article className="card goal-map"><SectionHead title="Distância até a meta" subtitle="Cada atleta contra seu próprio objetivo" action={descending ? "Maior gap primeiro" : "Menor gap primeiro"} onAction={() => setDescending((value) => !value)} /><div className="goal-athletes">{goalAthletes.map((athlete, index) => <button key={athlete.id} onClick={() => onAthlete(athlete.id)}><Avatar initials={athlete.initials} color={athlete.color} small /><div><span><b>{athlete.name}</b><small>{athlete.goalEvent}</small></span><div><i style={{ width: `${82 - index * 8}%` }} /><em style={{ left: `${82 - index * 8}%` }} /></div></div><strong>{athlete.gap}</strong></button>)}</div></article>
      <article className="card roster-performance"><SectionHead title="Visão do elenco" subtitle="Metas, presença e habilidades" action={classic ? "Visão executiva" : "Visão clássica"} onAction={() => setClassic((value) => !value)} /><div className="performance-head"><span>ATLETA</span><span>GAP</span><span>PRES.</span><span>HABILIDADES</span></div>{athletes.map((athlete) => <button key={athlete.id} onClick={() => onAthlete(athlete.id)}><span><Avatar initials={athlete.initials} color={athlete.color} small /><span><b>{athlete.name}</b><small>{athlete.goalEvent ?? "Sem meta"}</small></span></span><strong>{athlete.gap ?? "-"}</strong><strong>{athlete.attendance}%</strong><span className="skill-pills">{athlete.skills.map((skill) => <i key={skill.key} className={skill.score >= 80 ? "high" : skill.score >= 65 ? "mid" : "low"}>{skill.key}</i>)}</span></button>)}</article>
      <article className="card recovery-map"><SectionHead title="Recuperação do elenco" subtitle="Readiness × carga aguda" /><div className="quadrant"><span className="axis-label y">READINESS</span><span className="axis-label x">CARGA AGUDA</span><div className="quad-label q1">Pronto para carga</div><div className="quad-label q2">Monitorar</div><div className="quad-label q3">Recuperar</div>{athletes.filter((a) => a.readiness).map((athlete, i) => <button key={athlete.id} onClick={() => onAthlete(athlete.id)} style={{ left: `${28 + i * 12}%`, bottom: `${22 + (athlete.readiness ?? 0) * .58}%`, background: athlete.color }} title={`Abrir ${athlete.name}`}>{athlete.initials}</button>)}</div></article>
    </section></>;
}

export function News({ onNavigate, onAthlete, onNotify }: { onNavigate: (view: AppView) => void; onAthlete: (id: string) => void; onNotify: (message: string) => void }) {
  const [filter, setFilter] = useState<"Prioridade" | "Todos" | "Resolvidos">("Prioridade");
  const [resolved, setResolved] = useState<string[]>([]);
  const visible = insights.filter((item) => filter === "Todos" || (filter === "Resolvidos" ? resolved.includes(item.id) : !resolved.includes(item.id) && ["critical", "warning", "video"].includes(item.type)));
  const markAllRead = () => { setResolved(insights.map((item) => item.id)); setFilter("Resolvidos"); onNotify("Todos os alertas foram marcados como resolvidos."); };
  return <><PageTitle kicker="CENTRAL DE DECISÕES" title="Novidades" subtitle="Alertas explicáveis, ordenados por impacto e sempre ligados a uma ação."><button className="secondary-button" onClick={() => onNavigate("settings")}><Settings size={17} />Preferências</button><button className="primary-button" onClick={markAllRead}><Check size={17} />Marcar como lidas</button></PageTitle>
    <section className="inbox-layout"><div className="card inbox-list"><div className="inbox-tabs">{(["Prioridade", "Todos", "Resolvidos"] as const).map((item) => <button key={item} className={filter === item ? "active" : ""} onClick={() => setFilter(item)}>{item}{item !== "Resolvidos" && <span>{item === "Prioridade" ? 3 : insights.length}</span>}</button>)}</div>{visible.map((item) => <article className="inbox-item" key={item.id}><span className={`insight-icon ${item.type}`}>{item.type === "critical" ? <HeartPulse size={19} /> : item.type === "video" ? <Film size={19} /> : item.type === "success" ? <Trophy size={19} /> : item.type === "account" ? <UserPlus size={19} /> : <Activity size={19} />}</span><div><div><b>{item.title}</b><small>{item.time}</small></div><p>{item.body}</p><button onClick={() => item.target === "videos" ? onNavigate("videos") : item.type === "account" ? onNotify("Convite reenviado para Gabriel.") : onAthlete(item.target)}>{item.action}<ArrowRight size={14} /></button></div><button className="icon-button" aria-label={`Resolver alerta: ${item.title}`} onClick={() => { setResolved((value) => [...new Set([...value, item.id])]); onNotify(`Alerta resolvido: ${item.title}`); }}><Check size={17} /></button></article>)}{!visible.length && <div className="empty-state"><CircleCheck size={28} /><strong>Nenhum alerta nesta visão</strong><p>As decisões resolvidas permanecem disponíveis para auditoria.</p></div>}</div><aside className="stack"><article className="card weekly-digest"><Sparkles size={22} /><span>RESUMO INTELIGENTE</span><h3>A semana em 60 segundos</h3><p>O volume subiu <b>6,8%</b> com boa aderência. Ana respondeu melhor ao bloco RP. Luiza precisa de recuperação antes do próximo estímulo AN.</p><button className="secondary-button" onClick={() => onNotify("Resumo completo aberto com carga, aderência, recuperação e próximos riscos.")}>Abrir resumo completo</button></article><article className="card rule-card"><SectionHead title="Motor de regras" subtitle="Automações ativas" action="Configurar" onAction={() => onNavigate("settings")} /><div><span><CircleCheck size={16} />Queda de volume</span><em>Ativo</em></div><div><span><CircleCheck size={16} />Readiness crítico</span><em>Ativo</em></div><div><span><CircleCheck size={16} />Sem vídeo recente</span><em>Ativo</em></div><div><span><CircleCheck size={16} />Meta se aproximando</span><em>Ativo</em></div></article></aside></section></>;
}

export function Integrations({ onNotify, onCreateConnection }: { onNotify: (message: string) => void; onCreateConnection: (provider?: "garmin" | "polar" | "apple") => void }) {
  const exportLogs = () => { downloadFile("logs-sincronizacao.csv", [csvRow(["Horário", "Conector", "Estado", "Eventos"]), csvRow(["29/08/2026 02:47", "Garmin", "sucesso", 42]), csvRow(["29/08/2026 02:44", "Polar", "sucesso", 31]), csvRow(["29/08/2026 02:41", "Apple Health", "simulado", 55])].join("\n")); onNotify("Logs de sincronização exportados."); };
  return <><PageTitle kicker="ECOSSISTEMA DE DADOS" title="Integrações" subtitle="Conectores versionados, consentimento por atleta e rastreabilidade total."><button className="secondary-button" onClick={exportLogs}><FileText size={17} />Logs de sincronização</button><button className="primary-button" onClick={() => onCreateConnection()}><Plus size={17} />Nova conexão</button></PageTitle>
    <div className="integration-summary"><div><Cloud size={21} /><span><b>5 atletas sincronizados</b><small>Última coleta há 3 minutos</small></span></div><div><RefreshCw size={21} /><span><b>128 eventos hoje</b><small>100% idempotentes</small></span></div><div><ShieldCheck size={21} /><span><b>Consentimentos válidos</b><small>LGPD · auditoria ativa</small></span></div></div>
    <section className="connector-grid">{connectors.map((connector) => <article className="card connector-card" key={connector.id}><div className="connector-head"><span className={`connector-mark ${connector.id}`}>{connector.mark}</span><div><h3>{connector.name}</h3><p>{connector.category}</p></div><span className={`connector-status ${connector.status}`}>{connector.status === "connected" ? "Conectado" : connector.status === "native" ? "Requer app" : "Disponível"}</span></div><p className="connector-note">{connector.note}</p><div className="capabilities"><span className={connector.read ? "yes" : "no"}><Download size={14} />Consumir dados</span><span className={connector.write ? "yes" : "no"}><Send size={14} />Enviar treino</span></div><div className="connector-footer"><span><Users size={15} />{connector.athletes} atleta{connector.athletes === 1 ? "" : "s"}</span><button onClick={() => connector.id === "garmin" || connector.id === "polar" || connector.id === "apple" ? onCreateConnection(connector.id) : onNotify(`${connector.name}: conector de leitura preparado para a fase de homologação real.`)}>{connector.status === "connected" ? "Gerenciar" : connector.status === "native" ? "Ver requisitos" : "Conectar"}<ArrowRight size={14} /></button></div></article>)}</section>
    <article className="card sync-architecture"><div className="architecture-copy"><span className="eyebrow accent">ARQUITETURA PREPARADA</span><h2>Uma camada comum, conectores independentes.</h2><p>Cada origem declara suas capacidades. A plataforma preserva o payload bruto, normaliza a atividade e impede duplicidade antes de recalcular carga.</p></div><div className="flow-diagram"><div><Watch size={20} /><span>Dispositivo</span></div><ArrowRight size={18} /><div><Cloud size={20} /><span>Conector</span></div><ArrowRight size={18} /><div><Database size={20} /><span>Normalização</span></div><ArrowRight size={18} /><div><Gauge size={20} /><span>AquaOS</span></div></div></article>
  </>;
}

export function ProgramSettings({ onNotify }: { onNotify: (message: string) => void }) {
  const [tab, setTab] = useState("Programa");
  const logoInput = useRef<HTMLInputElement>(null);
  const [logoName, setLogoName] = useState("");
  const copyInvite = async () => { try { await navigator.clipboard.writeText("https://aquaos.app/join/selecao-nacional"); onNotify("Link de convite copiado."); } catch { onNotify("Link selecionado para cópia manual."); } };
  const saveProgram = async () => { try { await apiRequest("/api/v1/manage/settings/program", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ organizationName: "Seleção Nacional de Natação", locale: "pt-BR", measurementSystem: "metric", primaryPool: "50 m", updatedBy: "Leonardo Martins" }) }); onNotify("Configurações do programa salvas e auditadas."); } catch (error) { onNotify(error instanceof Error ? error.message : "Falha ao salvar configurações"); } };
  const saveZones = async () => { try { await Promise.all(zoneDistribution.map(async (zone) => { const body = { id: zone.code.toLowerCase(), name: `${zone.code} · ${zone.label}`, code: zone.code, color: zone.color, pace: zone.pace, status: "active" }; try { return await apiRequest(`/api/v1/manage/zones/${zone.code.toLowerCase()}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); } catch { return apiRequest("/api/v1/manage/zones", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); } })); onNotify("Zonas atualizadas; histórico preservado."); } catch (error) { onNotify(error instanceof Error ? error.message : "Falha ao salvar zonas"); } };
  return <><PageTitle kicker="ADMINISTRAÇÃO" title="Configurações" subtitle="Identidade, método, comissão, zonas, privacidade e operação." />
    <section className="settings-layout"><aside className="settings-menu">{["Programa", "Comissão técnica", "Zonas de intensidade", "Identidade", "Notificações", "Privacidade e LGPD", "Conta"].map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</aside><div className="card settings-panel">
      {tab === "Programa" && <><SectionHead title="Programa de performance" subtitle="Configurações principais da organização" /><div className="form-grid"><label><span>Nome do programa</span><input defaultValue="Seleção Nacional de Natação" /></label><label><span>Idioma padrão</span><select defaultValue="pt-BR"><option value="pt-BR">Português (Brasil)</option><option>English</option><option>Español</option><option>Français</option></select></label><label><span>Sistema de medidas</span><select><option>Métrico · metros</option></select></label><label><span>Piscina principal</span><select><option>Olímpica · 50 m</option><option>Semiolímpica · 25 m</option></select></label></div><div className="settings-callout"><Sparkles size={20} /><div><b>Motor de carga ativo: DemoLoadEngine v1.4</b><p>Determinístico e identificado como demonstração. O método proprietário será validado com casos históricos antes da ativação.</p></div><button className="secondary-button" onClick={() => { downloadFile("contrato-motor-carga.json", JSON.stringify({ version: "1.4", status: "demo", inputs: ["prescrição", "execução", "zonas", "feedback"], outputs: ["métricas", "componentes", "explicação"] }, null, 2), "application/json"); onNotify("Contrato versionado do motor exportado."); }}>Ver contrato</button></div><button className="primary-button" onClick={() => void saveProgram()}>Salvar alterações</button></>}
      {tab === "Comissão técnica" && <><SectionHead title="Comissão técnica" subtitle="Papéis e acesso por organização" action="Convidar profissional" onAction={() => onNotify("Formulário de convite da comissão aberto com papel e nível de acesso.")} /><div className="staff-list">{[{ n: "Leonardo Martins", r: "Administrador · acesso total", i: "LM", c: "#0b927d" }, { n: "Camila Ferreira", r: "Treinadora · acesso total", i: "CF", c: "#7357ef" }, { n: "Rafael Nunes", r: "Fisiologista · somente leitura", i: "RN", c: "#397ac4" }].map((member) => <div key={member.n}><Avatar initials={member.i} color={member.c} /><span><b>{member.n}</b><small>{member.r}</small></span><span className="active-access"><StatusDot />Ativo</span><button className="icon-button" aria-label={`Gerenciar ${member.n}`} onClick={() => onNotify(`Permissões de ${member.n} abertas para edição.`)}><MoreHorizontal size={18} /></button></div>)}</div></>}
      {tab === "Zonas de intensidade" && <><SectionHead title="Zonas de intensidade" subtitle="Reordene, personalize ou aposente sem perder o histórico" action="Adicionar zona" onAction={() => onNotify("Nova zona adicionada ao fim da lista para configuração.")} /><div className="zone-settings">{zoneDistribution.map((zone) => <div key={zone.code}><span className="drag-handle">⋮⋮</span><i style={{ background: zone.color }} /><input defaultValue={zone.code} /><input defaultValue={zone.label} /><input defaultValue={zone.pace} /><button className="icon-button" aria-label={`Gerenciar zona ${zone.code}`} onClick={() => onNotify(`Opções de ordenar, aposentar e duplicar a zona ${zone.code} abertas.`)}><MoreHorizontal size={17} /></button></div>)}</div><button className="primary-button" onClick={() => void saveZones()}>Salvar zonas</button></>}
      {tab === "Identidade" && <><SectionHead title="Identidade da equipe" subtitle="Visível nos convites e na área do atleta" /><div className="identity-editor"><div className="logo-upload"><Waves size={30} /><input ref={logoInput} hidden type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={(event) => { const file = event.target.files?.[0]; if (file) { setLogoName(file.name); onNotify(`Logo ${file.name} carregado para revisão.`); } }} /><button onClick={() => logoInput.current?.click()}>{logoName ? "Trocar logo" : "Alterar logo"}</button>{logoName && <small>{logoName}</small>}</div><div className="form-grid"><label><span>Nome exibido</span><input defaultValue="Seleção Nacional" /></label><label><span>Cor principal</span><input defaultValue="#0C8F7C" /></label><label className="wide"><span>Link de convite</span><div className="copy-field"><input readOnly value="aquaos.app/join/selecao-nacional" /><button onClick={() => void copyInvite()}>Copiar</button></div></label></div></div><button className="primary-button" onClick={() => onNotify("Identidade atualizada e registrada na auditoria.")}>Salvar identidade</button></>}
      {tab === "Notificações" && <><SectionHead title="Notificações" subtitle="Tudo permanece no AquaOS; escolha o que também chega por e-mail" /><div className="toggle-list">{["Feedback em vídeo", "Respostas ao feedback", "Alertas de readiness", "Falhas de sincronização", "Mensagens da equipe", "Resumo semanal"].map((item, index) => <label key={item}><span><b>{item}</b><small>{index < 2 ? "Atletas e comissão" : "Somente comissão"}</small></span><input type="checkbox" defaultChecked={index !== 4} /><i /></label>)}</div><button className="primary-button" onClick={() => onNotify("Preferências de notificação salvas.")}>Salvar preferências</button></>}
      {tab === "Privacidade e LGPD" && <><SectionHead title="Privacidade e LGPD" subtitle="Dados esportivos e de saúde com governança explícita" /><div className="privacy-grid"><div><ShieldCheck size={21} /><b>Consentimentos</b><p>5 válidos · 1 pendente</p><button onClick={() => onNotify("Registro de consentimentos aberto com vigência e origem.")}>Gerenciar</button></div><div><Download size={21} /><b>Exportações</b><p>Portabilidade por atleta</p><button onClick={() => onNotify("Solicitação de portabilidade criada e auditada.")}>Solicitar</button></div><div><Lock size={21} /><b>Credenciais</b><p>Criptografadas e segregadas</p><button onClick={() => onNotify("Auditoria de credenciais concluída sem exposição de segredos.")}>Auditar</button></div><div><Database size={21} /><b>Retenção</b><p>Política configurável</p><button onClick={() => onNotify("Política de retenção aberta para configuração.")}>Configurar</button></div></div></>}
      {tab === "Conta" && <><SectionHead title="Sua conta" subtitle="Perfil, acesso e preferências pessoais" /><div className="account-profile"><Avatar initials="LM" color="#0b927d" /><div><b>Leonardo Martins</b><small>leonardo@aquaos.app · Brasil</small></div><button className="secondary-button" onClick={() => onNotify("Editor de perfil aberto.")}>Editar perfil</button></div><div className="form-grid"><label><span>Idioma</span><select><option>Português (Brasil)</option></select></label><label><span>Fuso horário</span><select><option>America/Sao_Paulo</option></select></label></div><button className="primary-button" onClick={() => onNotify("Preferências da conta salvas.")}>Salvar conta</button></>}
    </div></section>
  </>;
}
