export const openapi = {
  openapi: "3.0.3",
  info: { title: "RKF Coach API", version: "5.1.0-validation", description: "Contratos versionados para prescrição, carga, ingestão, pós-treino e operação de natação de alto rendimento." },
  servers: [{ url: "http://localhost:4000" }],
  paths: {
    "/api/v1/health": { get: { summary: "Health check" } },
    "/api/v1/auth/login": { post: { summary: "Cria sessão demo" } },
    "/api/v1/auth/logout": { post: { summary: "Encerra sessão" } },
    "/api/v1/auth/me": { get: { summary: "Usuário da sessão" } },
    "/api/v1/dashboard": { get: { summary: "Resumo do treinador" } },
    "/api/v1/workouts": { get: { summary: "Lista treinos" }, post: { summary: "Cria treino" } },
    "/api/v1/workouts/{id}/publish": { post: { summary: "Publica treino" } },
    "/api/v1/completed-workouts": { post: { summary: "Registra execução" } },
    "/api/v1/wellness": { post: { summary: "Registra bem-estar" } },
    "/api/v1/sync/{provider}": { post: { summary: "Executa simulador de dispositivo" } },
    "/api/v1/manage/{kind}": { get: { summary: "Lista registros gerenciáveis" }, post: { summary: "Cria registro gerenciável" } },
    "/api/v1/manage/{kind}/{id}": { get: { summary: "Detalha registro" }, patch: { summary: "Edita registro" }, delete: { summary: "Exclui registro" } },
    "/api/v1/uploads": { post: { summary: "Envia vídeo ou documento" } },
    "/api/v1/import/{kind}": { post: { summary: "Importa CSV, JSON ou FIT" } },
    "/api/v1/videos/{id}/analyze": { post: { summary: "Analisa movimento e gera métricas do vídeo" } },
    "/api/v1/videos/{id}/events": { post: { summary: "Adiciona marcador técnico ao vídeo" } },
    "/api/v1/rkf/dictionaries": { get: { summary: "Dicionários RKF: zonas, materiais, skills, regras, fases e distribuição" } },
    "/api/v1/rkf/bootstrap": { get: { summary: "Panorama operacional RKF com origem, gates e feature flags" } },
    "/api/v1/rkf/seed/status": { get: { summary: "Confere manifesto, contagens e hashes do staging RKF V5.1" } },
    "/api/v1/rkf/seed/stage": { post: { summary: "Registra conferência do staging canônico", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/seed/import": { post: { summary: "Importa a seed canônica por transação idempotente", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/cycles/generate": { post: { summary: "Gera plano de ciclo com fases, onda e volume múltiplo de 10" } },
    "/api/v1/rkf/sessions/compose": { post: { summary: "Gera prescrição RKF com hard rules, ranking e auditoria" } },
    "/api/v1/rkf/load/sessions": { post: { summary: "Calcula camadas de carga, monotonia, cold start e série ATL/CTL/TSB" } },
    "/api/v1/rkf/readiness/adapt": { post: { summary: "Decide adaptação por readiness com guardrails e mapeamento de zona" } },
    "/api/v1/rkf/response-index": { post: { summary: "Calcula índice de resposta individual" } },
    "/api/v1/rkf/evolution/assess": { post: { summary: "Classifica evolução/involução por comparabilidade" } },
    "/api/v1/rkf/ingestions": { get: { summary: "Lista ingestões RKF", security: [{ sessionCookie: [] }] }, post: { summary: "Recebe original, calcula hash e cria revisão", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/ingestions/{id}": { patch: { summary: "Cria correção versionada antes da confirmação", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/ingestions/{id}/confirm": { post: { summary: "Confirma campos críticos por identidade autenticada", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/ingestions/{id}/transition": { post: { summary: "Avança a máquina de estados RKF", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/prescriptions": { get: { summary: "Lista versões de prescrição", security: [{ sessionCookie: [] }] }, post: { summary: "Salva versão auditada para aprovação", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/prescriptions/{id}/approve": { post: { summary: "Publica snapshot imutável com papel derivado da sessão", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/results/sessions": { post: { summary: "Registra resultado hierárquico e compromete snapshot de carga", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/results/athletes/{athleteId}": { get: { summary: "Lista resultados do prontuário autorizado", security: [{ sessionCookie: [] }] } },
    "/api/v1/reports/athletes/{athleteId}.pdf": { get: { summary: "Exporta relatório auditável do atleta em PDF", security: [{ sessionCookie: [] }] } },
    "/api/v1/reports/athletes/{athleteId}.csv": { get: { summary: "Exporta o mesmo snapshot auditável em CSV", security: [{ sessionCookie: [] }] } },
  },
  components: { securitySchemes: { sessionCookie: { type: "apiKey", in: "cookie", name: "natacao_session" } } },
} as const;
