export const openapi = {
  openapi: "3.0.3",
  info: { title: "RKF Coach API", version: "5.1.0-validation", description: "Contratos versionados para prescrição, carga, ingestão, pós-treino e operação de natação de alto rendimento." },
  servers: [{ url: "http://localhost:4000" }],
  paths: {
    "/api/v1/health": { get: { summary: "Health check" } },
    "/api/v1/openapi.json": { get: { summary: "Contrato OpenAPI versionado" } },
    "/api/v1/auth/login": { post: { summary: "Cria sessão com e-mail ou CPF" } },
    "/api/v1/auth/logout": { post: { summary: "Encerra sessão", security: [{ sessionCookie: [] }] } },
    "/api/v1/auth/me": { get: { summary: "Usuário da sessão", security: [{ sessionCookie: [] }] } },
    "/api/v1/dashboard": { get: { summary: "Resumo do treinador", security: [{ sessionCookie: [] }] } },
    "/api/v1/athletes": { get: { summary: "Lista atletas", security: [{ sessionCookie: [] }] } },
    "/api/v1/groups": { get: { summary: "Lista grupos", security: [{ sessionCookie: [] }] } },
    "/api/v1/pools": { get: { summary: "Lista piscinas", security: [{ sessionCookie: [] }] } },
    "/api/v1/workouts": { get: { summary: "Lista treinos", security: [{ sessionCookie: [] }] }, post: { summary: "Cria treino", security: [{ sessionCookie: [] }] } },
    "/api/v1/workouts/{id}/publish": { post: { summary: "Publica treino", security: [{ sessionCookie: [] }] } },
    "/api/v1/completed-workouts": { get: { summary: "Lista execuções", security: [{ sessionCookie: [] }] }, post: { summary: "Registra execução", security: [{ sessionCookie: [] }] } },
    "/api/v1/wellness": { get: { summary: "Lista check-ins", security: [{ sessionCookie: [] }] }, post: { summary: "Registra bem-estar", security: [{ sessionCookie: [] }] } },
    "/api/v1/integrations": { get: { summary: "Lista conexões e jobs de sincronização", security: [{ sessionCookie: [] }] } },
    "/api/v1/sync/{provider}": { post: { summary: "Executa simulador de dispositivo", security: [{ sessionCookie: [] }] } },
    "/api/v1/manage": { get: { summary: "Panorama de recursos gerenciáveis", security: [{ sessionCookie: [] }] } },
    "/api/v1/manage/audit": { get: { summary: "Trilha de auditoria paginada", security: [{ sessionCookie: [] }] } },
    "/api/v1/manage/{kind}": { get: { summary: "Lista registros gerenciáveis", security: [{ sessionCookie: [] }] }, post: { summary: "Cria registro gerenciável", security: [{ sessionCookie: [] }] } },
    "/api/v1/manage/{kind}/{id}": { get: { summary: "Detalha registro", security: [{ sessionCookie: [] }] }, patch: { summary: "Edita registro", security: [{ sessionCookie: [] }] }, delete: { summary: "Exclui registro", security: [{ sessionCookie: [] }] } },
    "/api/v1/uploads": { post: { summary: "Envia vídeo ou documento", security: [{ sessionCookie: [] }] } },
    "/api/v1/import/{kind}": { post: { summary: "Importa CSV, JSON ou FIT", security: [{ sessionCookie: [] }] } },
    "/api/v1/videos/{id}/analyze": { post: { summary: "Analisa movimento e gera métricas do vídeo", security: [{ sessionCookie: [] }] } },
    "/api/v1/videos/{id}/events": { post: { summary: "Adiciona marcador técnico ao vídeo", security: [{ sessionCookie: [] }] } },
    "/api/v1/ai/status": { get: { summary: "Disponibilidade do assistente IA", security: [{ sessionCookie: [] }] } },
    "/api/v1/ai/chat": { post: { summary: "Conversa com assistente IA restrito ao contexto RKF", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/dictionaries": { get: { summary: "Dicionários RKF: zonas, materiais, skills, regras, fases e distribuição" } },
    "/api/v1/rkf/bootstrap": { get: { summary: "Panorama operacional RKF com origem, gates e feature flags" } },
    "/api/v1/rkf/release-gates": { get: { summary: "Executa os 36 release gates RKF e anexa evidências", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/seed/status": { get: { summary: "Confere manifesto, contagens e hashes do staging RKF V5.1" } },
    "/api/v1/rkf/seed/stage": { post: { summary: "Registra conferência do staging canônico", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/seed/import": { post: { summary: "Importa a seed canônica por transação idempotente", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/seed/files": { get: { summary: "Lista os dez arquivos canônicos com contagens, colunas, hashes e ativação", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/seed/files/{name}": { get: { summary: "Consulta com paginação e busca qualquer linha preservada da seed", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/migrations": { get: { summary: "Migrations versionadas aplicadas e pendentes", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/events": { get: { summary: "Catálogo versionado de eventos de domínio", security: [{ sessionCookie: [] }] } },
    "/api/v1/backup": { post: { summary: "Cria backup lógico transacional com checksum", security: [{ sessionCookie: [] }] } },
    "/api/v1/backup/{id}/verify": { get: { summary: "Verifica checksum de um backup registrado", security: [{ sessionCookie: [] }] } },
    "/api/v1/lgpd/athletes/{athleteId}/export": { get: { summary: "Exporta todos os dados do atleta (portabilidade LGPD)", security: [{ sessionCookie: [] }] } },
    "/api/v1/lgpd/athletes/{athleteId}/anonymize": { post: { summary: "Anonimiza PII preservando métricas auditáveis (LGPD)", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/fatigue/assess": { post: { summary: "Avalia fadiga por distância/especialidade com limiar de interrupção (G19)", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/fatigue/recovery-matrix": { get: { summary: "Matriz de recuperação interbloco por fase (G20)" } },
    "/api/v1/rkf/learning-history": { post: { summary: "Classifica histórico de aprendizagem sem alterar zona/modelo (§32.7)", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/athletes/{athleteId}/readiness": { get: { summary: "Readiness atual do atleta com guardrails", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/athletes/{athleteId}/load": { get: { summary: "Série crônica ATL/CTL/TSB e alertas do atleta", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/athletes/{athleteId}/load-layers": { get: { summary: "Camadas de carga prescrita/executada/interna persistidas", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/athletes/{athleteId}/next-prescription": { get: { summary: "Próxima prescrição publicada do atleta", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/athletes/{athleteId}/performance-trend": { get: { summary: "Tendência de desempenho por resultado", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/entitlements": { get: { summary: "Entitlements e feature flags do usuário", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/plans": { get: { summary: "Contrato formal dos quatro planos do produto (G25)", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/ui/contracts": { get: { summary: "Contratos e seeds de UI versionados (G27/G28)", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/ui/e2e-evidence": { post: { summary: "Publica evidência da suíte E2E para os gates G23/G24/G27/G28", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/ingestions/contracts": { get: { summary: "Os 8 contratos de ingestão nomeados (G35)", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/ingestions/apply-seeds": { post: { summary: "Aplica seeds de ingestão idempotentes por canal (G36)", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/ingestions/{id}/commit-external": { post: { summary: "Consolida ingestão confirmada como treino externo, fora da biblioteca (UAT-06)", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/prescriptions/{id}/revise": { post: { summary: "Revisão de publicada cria nova versão; snapshot imutável (UAT-08)", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/governance/decisions": { get: { summary: "Lista as doze decisões metodológicas formais", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/governance/decisions/{id}": { patch: { summary: "Versiona decisão metodológica com evidência e controle de concorrência", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/cycles/generate": { post: { summary: "Gera plano de ciclo com fases, onda e volume múltiplo de 10" } },
    "/api/v1/rkf/sessions/compose": { post: { summary: "Gera prescrição RKF com hard rules, ranking e auditoria" } },
    "/api/v1/rkf/sessions": { get: { summary: "Consulta a biblioteca de 910 sessões com filtros", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/sessions/{id}": { get: { summary: "Detalha sessão com blocos, unidades e auditoria de volume", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/load/sessions": { post: { summary: "Calcula camadas de carga, monotonia, cold start e série ATL/CTL/TSB" } },
    "/api/v1/rkf/readiness/adapt": { post: { summary: "Decide adaptação por readiness com guardrails e mapeamento de zona" } },
    "/api/v1/rkf/response-index": { post: { summary: "Calcula índice de resposta individual" } },
    "/api/v1/rkf/evolution/assess": { post: { summary: "Classifica evolução/involução por comparabilidade" } },
    "/api/v1/rkf/evolution/assess-set": { post: { summary: "Avalia um conjunto de sessões por chave comparável" } },
    "/api/v1/rkf/evolution/athletes/{athleteId}": { get: { summary: "Histórico de evolução do prontuário autorizado", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/ingestions": { get: { summary: "Lista ingestões RKF", security: [{ sessionCookie: [] }] }, post: { summary: "Recebe original, calcula hash e cria revisão", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/ingestions/{id}": { patch: { summary: "Cria correção versionada antes da confirmação", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/ingestions/{id}/confirm": { post: { summary: "Confirma campos críticos por identidade autenticada", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/ingestions/{id}/transition": { post: { summary: "Avança a máquina de estados RKF", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/prescriptions": { get: { summary: "Lista versões de prescrição", security: [{ sessionCookie: [] }] }, post: { summary: "Salva versão auditada para aprovação", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/prescriptions/{id}/approve": { post: { summary: "Publica snapshot imutável com papel derivado da sessão", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/prescriptions/{id}.pdf": { get: { summary: "PDF da prescrição publicada (modelo de piscina)", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/results/sessions": { post: { summary: "Registra resultado hierárquico e compromete snapshot de carga", security: [{ sessionCookie: [] }] } },
    "/api/v1/rkf/results/athletes/{athleteId}": { get: { summary: "Lista resultados do prontuário autorizado", security: [{ sessionCookie: [] }] } },
    "/api/v1/reports/athletes/{athleteId}.pdf": { get: { summary: "Exporta relatório auditável do atleta em PDF", security: [{ sessionCookie: [] }] } },
    "/api/v1/reports/athletes/{athleteId}.csv": { get: { summary: "Exporta o mesmo snapshot auditável em CSV", security: [{ sessionCookie: [] }] } },
  },
  components: { securitySchemes: { sessionCookie: { type: "apiKey", in: "cookie", name: "natacao_session" } } },
} as const;
